# Generated by Django 4.2.29 on 2026-03-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acceso", "0004_producto_descripcion_producto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula", models.CharField(max_length=20, unique=True)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("vendedor", "Vendedor"),
                            ("bodega", "Bodega"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(max_length=15)),
                ("direccion", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_contratacion", models.DateField(auto_now_add=True)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
