# Generated by Django 6.0.3 on 2026-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0006_sede_factura_iva_factura_numerofactura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("empleado", "Empleado")],
                default="empleado",
                max_length=20,
            ),
        ),
    ]
