# Generated by Django 6.0.3 on 2026-03-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0008_alter_detallepedido_preciounitario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="barrio_domicilio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="ciudad_domicilio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="costo_envio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="direccion_domicilio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="telefono_domicilio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_entrega",
            field=models.CharField(
                choices=[("sede", "Recoger en Sede"), ("domicilio", "Domicilio")],
                default="sede",
                max_length=10,
            ),
        ),
    ]
