# Generated by Django 6.0.3 on 2026-03-08 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TarifaParqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[("carro", "Carro"), ("moto", "Moto")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "precio_por_hora",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_por_dia",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=15)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_placa", models.CharField(max_length=10)),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[("carro", "Carro"), ("moto", "Moto")], max_length=10
                    ),
                ),
                ("color", models.CharField(max_length=30)),
                ("hora_entrada", models.DateTimeField(auto_now_add=True)),
                ("hora_salida", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "total_cobrado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "empleado_entrada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entradas",
                        to="acceso.empleado",
                    ),
                ),
                (
                    "empleado_salida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salidas",
                        to="acceso.empleado",
                    ),
                ),
            ],
        ),
    ]
