# Generated by Django 6.0.3 on 2026-03-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "idCategoria_Producto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombreCategoria", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "CategoriaProducto",
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                ("idDetalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "precioUnitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "DetallePedido",
            },
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                ("idDomicilio", models.AutoField(primary_key=True, serialize=False)),
                ("fechaDomicilio", models.DateField()),
                ("horaDomicilio", models.TimeField()),
                ("estadoDomicilio", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Domicilio",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                ("idFactura", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipoDocUsuario",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("numeroDoc", models.BigIntegerField(blank=True, null=True)),
                (
                    "valorUnitarioProducto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "totalPedido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fechaPedido", models.DateTimeField(blank=True, null=True)),
                ("fechaFactura", models.DateTimeField(auto_now_add=True)),
                (
                    "metodoDePago",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "Factura",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("idPedido", models.AutoField(primary_key=True, serialize=False)),
                ("fechaPedido", models.DateTimeField(auto_now_add=True)),
                ("horaPedido", models.TimeField(auto_now_add=True)),
                ("estadoPedido", models.CharField(default="Procesado", max_length=20)),
                ("metodoPago", models.CharField(max_length=30)),
                ("totalPedido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("codigopostal", models.CharField(max_length=10)),
                ("ciudad", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "Pedido",
            },
        ),
        migrations.CreateModel(
            name="Permisos",
            fields=[
                ("idPermisos", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descripcionPermiso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fechaAsignacion", models.DateTimeField(auto_now_add=True)),
                ("estadoPermiso", models.CharField(default="Activo", max_length=30)),
            ],
            options={
                "db_table": "Permisos",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idProducto", models.AutoField(primary_key=True, serialize=False)),
                ("nombreProducto", models.CharField(max_length=100)),
                (
                    "precioProducto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "estadoProducto",
                    models.CharField(default="Disponible", max_length=50),
                ),
                (
                    "idCategoria_Producto",
                    models.ForeignKey(
                        db_column="idCategoria_Producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="acceso.categoriaproducto",
                    ),
                ),
            ],
            options={
                "db_table": "Producto",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("idRol", models.AutoField(primary_key=True, serialize=False)),
                ("descripcionRol", models.CharField(max_length=50)),
                ("estadoRol", models.CharField(default="Activo", max_length=11)),
            ],
            options={
                "db_table": "Rol",
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("idUsuario", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipoDocUsuario",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("numDocUsuario", models.BigIntegerField(unique=True)),
                ("nombreUsuario", models.CharField(max_length=50)),
                (
                    "apellidosUsuario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "direccionUsuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telefonoUsuario", models.BigIntegerField(blank=True, null=True)),
                (
                    "correoUsuario",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("claveUsuario", models.CharField(max_length=100)),
                ("estadoUsuario", models.CharField(default="A", max_length=1)),
                (
                    "idRol",
                    models.ForeignKey(
                        db_column="idRol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="acceso.rol",
                    ),
                ),
            ],
            options={
                "db_table": "Usuarios",
            },
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="empleado_salida",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="empleado_entrada",
        ),
        migrations.DeleteModel(
            name="TarifaParqueo",
        ),
        migrations.AddField(
            model_name="factura",
            name="idPedido",
            field=models.OneToOneField(
                db_column="idPedido",
                on_delete=django.db.models.deletion.CASCADE,
                to="acceso.pedido",
            ),
        ),
        migrations.AddField(
            model_name="domicilio",
            name="idPedido",
            field=models.OneToOneField(
                db_column="idPedido",
                on_delete=django.db.models.deletion.CASCADE,
                to="acceso.pedido",
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="idPedido",
            field=models.ForeignKey(
                db_column="idPedido",
                on_delete=django.db.models.deletion.CASCADE,
                to="acceso.pedido",
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="idProducto",
            field=models.ForeignKey(
                db_column="idProducto",
                on_delete=django.db.models.deletion.CASCADE,
                to="acceso.producto",
            ),
        ),
        migrations.AddField(
            model_name="permisos",
            name="idRol",
            field=models.ForeignKey(
                db_column="idRol",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acceso.rol",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="idUsuario",
            field=models.ForeignKey(
                db_column="idUsuario",
                on_delete=django.db.models.deletion.CASCADE,
                to="acceso.usuarios",
            ),
        ),
        migrations.DeleteModel(
            name="Empleado",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
