# Generated by Django 6.0.3 on 2026-03-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0002_categoriaproducto_detallepedido_domicilio_factura_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Domicilio",
        ),
    ]
