# Generated by Django 6.0.3 on 2026-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0003_delete_domicilio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
