# Generated by Django 6.0.3 on 2026-03-18 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0005_empleado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                ("idSede", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("ciudad", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Sede",
            },
        ),
        migrations.AddField(
            model_name="factura",
            name="iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="numeroFactura",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("vendedor", "Vendedor")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                db_column="idSede",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acceso.sede",
            ),
        ),
        migrations.CreateModel(
            name="CarritoItem",
            fields=[
                ("idCarritoItem", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("agregado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "idProducto",
                    models.ForeignKey(
                        db_column="idProducto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceso.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrito",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CarritoItem",
                "unique_together": {("usuario", "idProducto")},
            },
        ),
    ]
