# Generated by Django 6.0.3 on 2026-03-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0007_alter_empleado_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallepedido",
            name="precioUnitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="salario",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="factura",
            name="iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="totalPedido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="valorUnitarioProducto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="totalPedido",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precioProducto",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
