# Generated by Django 6.0.5 on 2026-05-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0009_pedido_barrio_domicilio_pedido_ciudad_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('estadoVenta', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada'), ('pendiente', 'Pendiente')], default='completada', max_length=20)),
                ('metodoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_presenciales', to='acceso.usuarios')),
                ('empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='acceso.empleado')),
                ('sede', models.ForeignKey(db_column='idSede', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_sede', to='acceso.sede')),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoVenta',
            fields=[
                ('idNota', models.AutoField(primary_key=True, serialize=False)),
                ('fechaNota', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('devolucion', 'Devolución de producto'), ('error_cobro', 'Error en cobro'), ('anulacion', 'Anulación total')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('montoDevuelto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='acceso.empleado')),
                ('venta', models.OneToOneField(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='acceso.venta')),
            ],
            options={
                'db_table': 'NotaCreditoVenta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuentoLinea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='acceso.producto')),
                ('venta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='acceso.venta')),
            ],
            options={
                'db_table': 'DetalleVenta',
            },
        ),
    ]
